name: Infinitifall
version: '${project.version}'
main: com.justinschaaf.infinitifall.Infinitifall
api-version: 1.19
author: "justinhschaaf"
website: "https://github.com/justinhschaaf/Infinitifall"
folia-supported: true
commands:
    infinitifall:
        # Syntax based off of https://minecraft.fandom.com/wiki/Commands#Command_guide
        usage: "/infinitifall (reload)"
        description: "Main command for Infinitifall"
        aliases:
            - if
permissions:
    infinitifall.reload:
        description: "Reload configuration"
        default: op
